### ISSUE TITLE
ToDo: Graphics

### ISSUE THREAD

**Issue by morrowdavidson** [I3uckwheat/attack-of-the-clowns#3]
## Style guide
- [x] Sample from each section below

## Background
- [ ] Crowd
- [ ] Pole
- [ ] Ring 
- [ ] Tent ceiling

## Characters
- [ ] Playable
- [ ] Enemies (3 clown variations with changeable colors )

## Misc
- [ ] Weapons or different body parts for different abilities. 
- [ ] Crate or circus stand

## Maybes
- [ ] Barrel
- [ ] Tight rope
- [ ] Clown Car
- [ ] Elephant
- [ ] Lion
- [ ] Lion tamer 
- [ ] Stunt biker
- [ ] Tight rope walker
- [ ] Juggler
- [ ] Knife thrower
- [ ] Sword swollower
- [ ] Fire rings

**Comment by morrowdavidson** [comment]
![StyleGuide](https://user-images.githubusercontent.com/44884803/54665415-3ffabe00-4aa4-11e9-86ea-7baa7393a060.png)
Style guide - minus the crowd
